spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comprasdb?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/comprasdb?useTimezone=true&serverTimezone=UTC
    schemas: comprasdb
    user: postgres
    password: postgres123
    baseline-on-migrate: true
  jackson:
    time-zone: GMT-3
    date-format: yyyy-MM-dd HH:mm:ss