spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/comprasdb
    username: postgres
    password: postgres123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    show-sql: true