version: '3.8'

services:
  db:
    container_name: SESDB
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/01_CreateSchema.sql:/docker-entrypoint-initdb.d/01_CreateSchema.sql
      - ./sql/02_InitLogback.sql:/docker-entrypoint-initdb.d/02_InitLogback.sql
